name: Build Skyve

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: msbuild Skyve.sln /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build
      run: msbuild Skyve.sln /p:Configuration=${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Skyve-${{ matrix.configuration }}
        path: Skyve/Skyve.App/bin/${{ matrix.configuration }}/
